import Image from 'next/image'
import Head from 'next/head'
import styled from 'styled-components'
import DemoForm from '../components/form'

const Container = styled.div`
  max-width: 1170px;
  margin: 0 auto;
  background-color: white;
  height: 100%;
  border: var(--dark-gray) 1px solid;
  padding: 0 20px;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Tawkify React Coding Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <div>
          <header className="text-center">
            <Image src="/logo.png" width="200" height="200" />
            <h1>Tawkify Coding Challenge</h1>
          </header>
          <main>
            <DemoForm className="mt-7" />
          </main>
        </div>
      </Container>
    </>
  )
}
